---
title: "Results Coding"
author: "Annie Whamond"
date: "2023-08-28"
output: html_document
---
# Load processed data files
```{r}

d_journals <- read_csv(here('data','processed','d_journals.csv'))
d_articles <- read_csv(here('data','processed','d_articles.csv'))

```

# Journal Policy Overview
```{r}

d_journals_anyPPC <- d_journals %>%
  filter(ppc_type == "A") %>%
  filter(is_empirical == "TRUE")

table(d_journals_anyPPC$sample_id)
table(d_journals_anyPPC$has_ppc)
table(d_journals_anyPPC$has_ppc, d_journals_anyPPC$sample_id)

```


# Calculate CIs for YES 
```{r}
library(binom)

# Prominent Sample data
prominentSuccess <- 38
randomSuccess <- 23
totalSuccess <- 57

sample_size <- 100
totalSample <- 189
confidence_level <- 0.95

# Calculate the Wilson confidence interval
ci_prominent <- binom.confint(prominentSuccess, sample_size, method = "wilson", conf.level = confidence_level)
ci_random <- binom.confint(randomSuccess, sample_size, method = "wilson", conf.level = confidence_level)
ci_total <- binom.confint(totalSuccess, totalSample, method = "wilson", conf.level = confidence_level)

# Print the confidence interval
print(ci_prominent)
print(ci_random)
print(ci_total)
```
# Look at PPC names
```{r}

table(d_journals$ppc_name)

```



# Look at PPC length limitations
```{r}

# Removes journals that do not offer any PPC 
 d_PPConly <- d_journals %>%
   filter(has_ppc == "YES")

#Look at stated length limits
PPC_length <- d_PPConly %>%
  filter(!is.na(ppc_length)) %>%
  filter(ppc_length != "NO") %>%
  filter(ppc_length != "NOT STATED")


table(PPC_length$ppc_length, PPC_length$ppc_name)
```



# Look at PPC time limitations
``` {r}
PPC_time <- d_PPConly %>%
  filter(!is.na(ppc_time)) %>%
  filter(ppc_time != "NOT STATED")

table(PPC_time$ppc_time, PPC_time$ppc_name)
  
```




# Bar graph of PPC by COPE

```{r}
library(ggplot2)
library(RColorBrewer)

# Create bar plot
d_journals %>%  
  mutate(has_ppc = case_when(
    has_ppc == 'ARCHIVE' ~ 'YES',
    has_ppc == 'NO EXPLICIT' | has_ppc == 'NO IMPLICIT' ~ 'NO',
    TRUE ~ has_ppc
    )) %>%
  filter(ppc_type == "A") %>%
  filter(has_ppc == "YES" | has_ppc == "NO") %>%
  ggplot() +
geom_bar(
  mapping = aes(x=has_ppc, fill = cope),
  stat = "count",
  position = "stack",
  colour = "black",
  just = 0.5,
  width = 0.7,
  na.rm = FALSE,
  orientation = NA,
  show.legend = TRUE,
  inherit.aes = TRUE
) +
  theme_bw() +
  scale_fill_brewer(palette = "Blues") +
  labs(title = "Journal PPC Acceptance by COPE membership", x = "Accepts PPC", y = "Count")
```








